# Settings of the plugins. (The plugins should be stored in script/plugins)

# min_filter fills in minimum value around the invalid cell.
min_filter:                                   
  enable: False                                # weather to load this plugin
  fill_nan: False                             # Fill nans to invalid cells of elevation layer.
  is_height_layer: True                       # If this is a height layer (such as elevation) or not (such as traversability)
  layer_name: "min_filter"                    # The layer name.
  extra_params:                               # This params are passed to the plugin class on initialization.
    dilation_size: 1                         # The patch size to apply
    iteration_n: 30                           # The number of iterations
# Apply smoothing.
smooth_filter:                                
  enable: False
  fill_nan: False
  is_height_layer: True
  layer_name: "smooth"
  extra_params:
    input_layer_name: "min_filter"
# Apply inpainting using opencv
inpainting:                                   
  enable: False
  fill_nan: False
  is_height_layer: True
  layer_name: "inpaint"
  extra_params:
    method: "telea"                           # telea or ns
# Apply smoothing for inpainted layer
smooth_filter_1:                                
  type: "smooth_filter"
  enable: False
  fill_nan: False
  is_height_layer: True
  layer_name: "smooth_1"
  extra_params:
    input_layer_name: "inpaint"
step_filter:
  type: "step_filter"
  enable: True
  fill_nan: False
  is_height_layer: False
  layer_name: "step"
  extra_params:
    critical_cell_num: 4
    critical_value: 0.29
    first_window_radius: 0.06
    second_window_radius: 0.06
    map_resolution: 0.03
    input_layer_name: "elevation"
cutter_filter:
  type: "cutter_filter"
  enable: True
  fill_nan: False
  is_height_layer: True
  layer_name: "cutter"
  extra_params:
    first_num: 6
    MaxGap: 0.30
    CutterInputLayer: "elevation"
step_cutter_filter:
  type: "step_cutter_filter"
  enable: True
  fill_nan: False
  is_height_layer: False
  layer_name: "step_cutter"
  extra_params:
    critical_cell_num: 4
    critical_value: 0.29
    first_window_radius: 0.06
    second_window_radius: 0.06
    map_resolution: 0.03
    StepCutterFilterInputLayer: "cutter"
cutter_filter_second:
  type: "cutter_filter_second"
  enable: False
  fill_nan: False
  is_height_layer: True
  layer_name: "cutter2"
  extra_params:
    first_num: 6
    MaxGap: 0.30
    CutterInputLayer2: "cutter"
sample_filter:
  type: "sample_filter"
  enable: True
  fill_nan: False
  is_height_layer: False
  layer_name: "cum_prob"
  extra_params:
    blur_radiu_num: 79
    sigma_num: 13
    StepThreshold: 0.7
    SampleInputLayer1: "elevation"
    SampleInputLayer2: "step"
sample_filter2:
  type: "sample_filter2"
  enable: True
  fill_nan: False
  is_height_layer: False
  layer_name: "cum_prob_rowwise_hack"
  extra_params:
    blur_radiu_num: 79
    sigma_num: 13
    StepThreshold: 0.7
    SampleInputLayer1: "elevation"
    SampleInputLayer2: "step"
